version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      timeout: 180
      runas: ubuntu
